name = "gorilla/mux"
title = "Gorilla/Mux"
group = "servers/http"
description = "Package gorilla/mux implements a request router and dispatcher for matching incoming requests to their respective handler"
packages = [ "github.com/gorilla/mux" ]
